### ISSUE TITLE
there's a release/app/yarn.lock - do we use it?

### ISSUE THREAD

**Issue by SvenDowideit** [workbenchapp/solana-workbench#108]
@nathanleclaire https://github.com/workbenchapp/solana-workbench/blob/main/release/app/yarn.lock

https://github.com/workbenchapp/solana-workbench/security/dependabot

it's triggering some security reports, and i was under the impression we don't use yarn - so if we can delete it \0/

**Comment by nathanleclaire** [comment]
shouldn't, delete away

**Comment by SvenDowideit** [comment]
done
