### ISSUE TITLE
AccountView Token support

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#114]
this is #123

We will be adding the feature to mint tokens (both fungible and non-fungible) via Workbench, and there are also lots of built-in tokens on mainnet etc. However, Workbench's account support and rendering of what's happening is pretty basic and low level right now and doesn't understand tokens.

This type of view ideally should show existing token balances, etc., or mint properties if it's a mint:

<img width="722" alt="Screen Shot 2022-05-06 at 12 27 52 PM" src="https://user-images.githubusercontent.com/1476820/167204850-080104fb-ea94-480c-a3a3-a3fe567ca1d1.png">

Likewise once https://github.com/workbenchapp/solana-workbench/pull/73 lands it should show probably show diffs of tokens/SOL in txns like how explorer does

<img width="1117" alt="Screen Shot 2022-05-06 at 12 29 24 PM" src="https://user-images.githubusercontent.com/1476820/167213979-affb38de-bb4e-4525-94ca-2961d2d87071.png">

**Comment by SvenDowideit** [comment]
yup, I'm intending to add something for the v0.4.0 headline #63 - so that I know that the create token (and transfer token) works
