### ISSUE TITLE
UI tidying

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#116]
The UI / styling could use some love. e.g.:

![image](https://user-images.githubusercontent.com/1476820/167214980-f2cd58ff-d3dd-4cf0-87f1-e914bd225139.png)

**Comment by SvenDowideit** [comment]
iirc, I've added table headers with user selectable sorting in https://github.com/workbenchapp/solana-workbench/pull/86

which then also removes some of the extra text from the rows.

**Comment by nathanleclaire** [comment]
The UI has diverged a lot from this issue's creation so I'm going to close in favor of more specific ones
