### ISSUE TITLE
Workbench spams getAccountInfo in higher environments 

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#118]
Workbench gets blocked from mainnet (I think?) pretty doggone quick, probably because we're slamming `getAccountInfo` so frequently across thousands of accounts https://github.com/workbenchapp/solana-workbench/blob/867b9e0041f9907dffb1b78ca671ad59c4b60fca/src/renderer/components/ProgramChange.tsx#L55-L57

<img width="1174" alt="Screen Shot 2022-05-06 at 2 12 40 PM" src="https://user-images.githubusercontent.com/1476820/167217672-43730097-22ac-421e-9a7c-f9e0030f8cd5.png">

We could bundle these calls up into one [getMultipleAccounts](https://docs.solana.com/developing/clients/jsonrpc-api#getmultipleaccounts) that we call every so often, or probably just remove this part (after all, we're subscribing to changes in lamports, so if a change happens, we already get a notification pushed, why not use that?)

**Comment by SvenDowideit** [comment]
I'd like to push this to "next release" - its not a regression, but something we're actively working towards improving.

yes, imo we need to do both - I added code to getAccounts to use the pushed info when its up to date enough (and I'm guessing its not got enough slack), and at the same time, started accounts should be rolled up into a getMultipleAccount

**Comment by SvenDowideit** [comment]
the worst offenders are the not-on-chain accounts - I wasn't caching those. playing with it in rebasing #86
