### ISSUE TITLE
Add ability to manually add pinned account

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#122]
There used to be a way to add an account to the list of pinned accounts manually, e.g., to track your wallet in devnet or mainnet -- 

https://youtu.be/GdzdUdran7Y?t=59

This should be added back in

**Comment by nathanleclaire** [comment]
ah, I think that's what this is?

<img width="410" alt="Screen Shot 2022-05-09 at 3 07 38 PM" src="https://user-images.githubusercontent.com/1476820/167506694-a582068f-14a0-47f9-8d4f-2a7a360fabd4.png">

**Comment by SvenDowideit** [comment]
yup, that is why i made it :)

**Comment by SvenDowideit** [comment]
implemented during dev for 0.3
