### ISSUE TITLE
Native dependency @solana/wallet-adapter-wallets in root package.json rather than in release/app/package.json

### ISSUE THREAD

**Issue by sammanadh** [workbenchapp/solana-workbench#136]
## Expected Behavior
Installing packages in root directory tries to install ```@solana/wallet-adapter-wallets```. But it should only be installed inside ```release/app```

I was trying to setup this project locally and installing packages in root directory produces an error. I removed native dependencies form root directory's ```package.json``` and placed it inside ```./release/app/package.json```, and now the installation works fine. 
## Current Behavior
Installing dependencies produces the following message and results in error
```
 Webpack does not work with native dependencies.
@solana/wallet-adapter-wallets is a native dependency and should be installed inside of the "./release/app" folder.
 First, uninstall the packages from "./package.json":
npm uninstall your-package
 Then, instead of installing the package to the root "./package.json":
npm install your-package
 Install the package to "./release/app/package.json"
cd ./release/app && npm install your-package
```

## Steps to Reproduce
1. clone the project
2. run ```npm install --legacy-peer-deps``` in the root directory of the project.

**Comment by nathanleclaire** [comment]
thx for the report! will check it out and get to you

**Comment by nathanleclaire** [comment]
Yup, I can dupe.

Would you like to put in a pull request for that fix?

**Comment by SvenDowideit** [comment]
I think this has been resolved with the vite port pr?
