### ISSUE TITLE
Update Docker images to 1.10.*

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#141]

**Comment by SvenDowideit** [comment]
https://hub.docker.com/repository/docker/daonetes/solana-amman/tags?page=1&ordering=last_updated built from https://github.com/workbenchapp/solana-validator

**Comment by nathanleclaire** [comment]
You're set as owner on https://hub.docker.com/orgs/cryptoworkbench . Let's keep publishing the images there please

**Comment by SvenDowideit** [comment]
i am now :)
