### ISSUE TITLE
Lifecycle of amman / container workflow 

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#160]
re: https://github.com/workbenchapp/solana-workbench/pull/149

There are some outstanding Qs we want to document about how Amman workflow should work:

- [x] We assume one container, is there a way we can still fetch logs and display them pretty?
- [ ] move to `tee`ing the `amman start` output to a file, and `docker exec ... tail -f` to get the logs after restart
-

**Comment by SvenDowideit** [comment]
the #149 that was merged fetches the Amman logs if the validator was started during the current workbench session - its basically streaming the output of the `docker exec solana amman start` - but when you restart workbench, that becomes unavailable.

need to replace that with `tee-ing` that output to a file, and using `docker exec solana tail -f outputfile` (closing #170 dupe)

#178 is imo a good start on making it pretty :)

**Comment by nathanleclaire** [comment]
This feels kinda vague now, gonna close and we can open new more specific ones if we want
