### ISSUE TITLE
Transfer SOL should be associated with wallet

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#185]
it's in account view atm, a bit odd since you can only use the wallet 

<img width="458" alt="Screen Shot 2022-07-07 at 7 40 11 PM" src="https://user-images.githubusercontent.com/1476820/177906108-b36671b0-bb3d-42cc-85f1-891e04181458.png">

**Comment by nathanleclaire** [comment]
Sure -- In the AccountView for each account we have this component, "Transfer SOL", which implies that you can transfer SOL to/from that account. But the operation is only possible for the accounts for which we have private keys, and mainly, when we do operations with priv keys in Workbench, we are expecting to use the selected wallet up top. So it would make more sense to have a dropdown for Transfer SOL in the top bar that sends from the wallet, instead of in each individual account view.

**Comment by SvenDowideit** [comment]
imo its nice to have it i the account view, but the UX would then change to "send SOL to this account", where the FROM==wallet-adapter-account, and TO==account selected in AccountView (right pane).

that way, there's no real need for copy&paste, or typing (and we don't get asked why super.sol Solana Name Service names don't work)

**Comment by sammanadh** [comment]
I do agree with sven that its better to keep the button where it currently is, but renaming it to "send SOL" and making the target account input read only. That way I think user will get the feeling that the button is to send sol to the selected account. But also, I think there needs to be another element using which user could just type or paste the target account. That way the user wouldn't have to filter through the accounts list.

**Comment by SvenDowideit** [comment]
closed by #219 ?
