### ISSUE TITLE
Differentiate "Network not Available" and "Loading" - and use a toast when changing networks

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#195]
Nitpicky, but I wish we showed a spinner when attempting to contact the network instead of "Network not Available". Devnet, testnet usually are available and just take a second to load, but we flash "Network not Available" in the meantime. Localnet on the other hand often is genuinely unavailable.

**Comment by SvenDowideit** [comment]
oh, interesting point too - should really flush the account cache too (or make one per network, in case the user's flicking between both to see something)
