### ISSUE TITLE
Error: IDL not found and unable to find account

### ISSUE THREAD

**Issue by SvenDowideit** [workbenchapp/solana-workbench#207]
![](https://user-images.githubusercontent.com/1476820/178388329-759e473c-f14e-45e1-b635-dfa7d0e203e0.png)

from #123

**Comment by SvenDowideit** [comment]
The "Error: Unable to find account" looks to be due to trying to find token metadata that isn't there.

and because I returned that as a throw Error(), react keeps retrying

will probably be addressed with some changes i'm doing for #215

**Comment by nathanleclaire** [comment]
IDL not found is normal, from Anchor decode. We need a check in the decode section to skip anchor decode attempt if it’s Token Program owner like it does for system program

**Comment by SvenDowideit** [comment]
ah, roger - so the real regression is the unable to find account 👍
