### ISSUE TITLE
getAccountInfo (jsonParsed=true) gets us throttled quickly when watching an account with lots of tokens

### ISSUE THREAD

**Issue by SvenDowideit** [workbenchapp/solana-workbench#264]
related to testing #261

I was hoping that the getParsedAccount() calls would be sufficiently ok, but on main-net I can get myself kicked off pretty quickly.

its plausible that we need to make a PR to allow the `jsonParsed` option on `getMultipleAccountsInfo` - @jacobcreech ? :D

This is made worse at the start, because it takes a few minutes to get to a steady state :/

this is likely to be a "defer to a later release"

mmm, as a devnet example - when I go to view `Fr8usJRe8PVMyw4xcLHZ4XZLTLeVuRabV45NR4rsY5r`, it does 16 `getParsedAccount()` requests to show the ATA, Mint and Metaplex Metadata (for the 5 tokens that account has on devnet)

**Comment by nathanleclaire** [comment]
Hmm ... can we turn off the related token account querying in AccountView for now (0.4.0, 0.4.1), or at least rein in the requests?

It's a shame that we're back to getting banned from higher nets easily, cause it limits the utility of other features like Anchor account decode.
