### ISSUE TITLE
sol amount broken in inspect tab

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#32]
<img width="329" alt="Screen Shot 2022-03-03 at 3 48 34 PM" src="https://user-images.githubusercontent.com/1476820/156650579-1c658cb7-8cf4-4ca5-bebe-0f2d79607de1.png">

edit: this is only _right_ after we create the initial wallets. i think once the txn is confirmed it's fine

**Comment by SvenDowideit** [comment]
I need to test this - it may be resolved with the merge back from web-workbench

**Comment by SvenDowideit** [comment]
fixed in development
