### ISSUE TITLE
wallets not created on first load if validator not running

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#59]
Silly of me to not have thought about this, but if there's no validator going when you first start up the workbench, the account creation won't work. You have to tab over to another page and go back to the accounts page after starting one

(Really we should probably just go and run one though)

**Comment by SvenDowideit** [comment]
I sidestepped this by adding UI buttons to do this manually, and the wallet-adapter integration - and you did some things to init a new local validator from saved accounts - so I'm going to label this as 0.4.0-ish
