### ISSUE TITLE
Fix analytics

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#88]
This is hosed at the moment

<img width="510" alt="Screen Shot 2022-04-18 at 2 04 55 PM" src="https://user-images.githubusercontent.com/1476820/163877986-af80a402-6ac8-4b98-ae7c-fe6ca1b51821.png">
<img width="988" alt="Screen Shot 2022-04-18 at 2 04 41 PM" src="https://user-images.githubusercontent.com/1476820/163877991-a07df54f-4f54-43c6-b01d-db4874427e3f.png">

**Comment by SvenDowideit** [comment]
is this #91 ? - asked @nathanleclaire for credentials so i can test

**Comment by nathanleclaire** [comment]
yup! i'm going to close, then we can re-open if something seems b0rked
