### ISSUE TITLE
v0.3.0 TODOs

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#89]
- [ ] Fix or remove program filter: issue #103
- [x] Layout fixes (overflow not handled correctly by logs and transaction view) -- https://github.com/workbenchapp/solana-workbench/pull/99
- [x] Fix analytics -- https://github.com/workbenchapp/solana-workbench/pull/91
- [x] Remove non-functional components (Connect to Wallet, Import Account, pause) -- https://github.com/workbenchapp/solana-workbench/pull/90
- [x] Styling on account list items (should not alternate gray/white as it's confusing given gray == hover, selected item should be highlighted blue) -- https://github.com/workbenchapp/solana-workbench/pull/90

**Comment by SvenDowideit** [comment]
close, tracking this using milestones: https://github.com/workbenchapp/solana-workbench/milestone/1

**Comment by nathanleclaire** [comment]
🎉

**Comment by nathanleclaire** [comment]
Hate to do this to ya, but I realized there's one more we should do before SHIPIT --

- [ ] Bump Docker images to latest Solana 1.9.x

**Comment by nathanleclaire** [comment]
i'm workin on it, PR inbound...

**Comment by SvenDowideit** [comment]
don't mention it here :) just add the 0.3.0 milestone :p

https://github.com/workbenchapp/solana-workbench/milestone/1
